name: push_to_ghcr

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: 5/debian-10
          push: true
          tags: ghcr.io/itsjwala/wordpress:fmd
